package br.cefet.trab.oficinamecanica.view.produto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import br.cefet.trab.oficinamecanica.dao.ProdutoDao;
import br.cefet.trab.oficinamecanica.entidade.Produto;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Interface de selecionar produtos
 * @author arthur
 */
public class ProdutoSelecionarJDialog extends javax.swing.JDialog {
    private int qtd = 0;

    public int getQtd() {
        return qtd;
    }
    private Produto produto = null;

    public Produto getProduto() {
        return this.produto;
    }


    /**
     * Creates new form TesteJFrame
     * @param owner descricao
     * @param modal descricao
     */
    public ProdutoSelecionarJDialog(JFrame owner, boolean modal) {
        super(owner, modal);

        initComponents();

        ProdutoDao dao = new ProdutoDao();

        List<Produto> pList = new LinkedList<>();

        try {

            pList = dao.consultarTodos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar todos os Produtos: " + ex.getMessage());
        }

        preencherJTable(pList);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Nome:");
        jPanel4.add(jLabel1);

        jTextField1.setColumns(20);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField1);

        jLabel2.setText("Quantidade :");
        jPanel4.add(jLabel2);

        jTextField2.setEditable(false);
        jTextField2.setColumns(5);
        jPanel4.add(jTextField2);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Selecionar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == 10) {
            List<Produto> pList = new LinkedList<>();

            try {
                ProdutoDao dao = new ProdutoDao();
                pList = dao.consultarPorNome(jTextField1.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao consultar todos os Produtos: " + ex.getMessage());
            }

            preencherJTable(pList);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jButton3.setEnabled(true);
        jTextField2.setEditable(true);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean permisao = true;
       try {
             int qtds = Integer.parseInt(jTextField2.getText());

            int linha = jTable1.getSelectedRow();
            DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
            int cod = getCodProdutoFromTable();

            try {
                ProdutoDao pDao = new ProdutoDao();
                this.produto = pDao.consultarPorCod(cod);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao consultar Produto com cod (" + cod + "):-" + ex.getMessage());
            }
            if (qtds > this.produto.getQuantidade()) {
                JOptionPane.showMessageDialog(this, "A quantidade informada é maior que a quantidade disponivel.");
                this.produto = null;
                this.jButton3.setEnabled(false);
            } else {
                    qtd = (qtds);
                    this.produto.setQtdVenda(qtds);
                    this.setVisible(false);
                    this.dispose();
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Quantidade inserida invalida -"  );
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.produto = null;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public int getCodProdutoFromTable() {
        int linha = jTable1.getSelectedRow();

        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

        String codStr = tModel.getValueAt(linha, 0).toString();
        int cod = Integer.parseInt(codStr);

        return cod;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelecionarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelecionarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelecionarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoSelecionarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoSelecionarJDialog(null, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void preencherJTable(List<Produto> pList) {
        String[] colunas = new String[]{"Cod.", "Nome", "Preço", "Quantidade"};

        String[][] dados = new String[pList.size()][4];
        for (int i = 0; i < pList.size(); i++) {
            Produto p = pList.get(i);
            dados[i][0] = p.getCdproduto() + "";
            dados[i][1] = p.getNome();
            dados[i][2] = Double.toString(p.getPreco());
            dados[i][3] = p.getQuantidade() + "";
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                dados, colunas
        ));

        jButton3.setEnabled(false);
    }
}
