/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.trab.oficinamecanica.view.venda;

import br.cefet.trab.oficinamecanica.dao.PVProdutoDao;
import br.cefet.trab.oficinamecanica.dao.ProdutoDao;
import br.cefet.trab.oficinamecanica.dao.SVServicoDao;
import br.cefet.trab.oficinamecanica.dao.ServicoDao;
import br.cefet.trab.oficinamecanica.dao.VendaDao;
import br.cefet.trab.oficinamecanica.entidade.Produto;

import br.cefet.trab.oficinamecanica.entidade.Servico;
import br.cefet.trab.oficinamecanica.entidade.Venda;
import br.cefet.trab.oficinamecanica.view.botoes.ButtonColumn;
import br.cefet.trab.oficinamecanica.view.PrincipalJFrame;
import br.cefet.trab.oficinamecanica.view.produto.ProdutoSelecionarJDialog;
import br.cefet.trab.oficinamecanica.view.servico.ServicoSelecionarJDialog;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Interface para alterar vendas
 * @author arthur
 */
public class AlterarVendaJDialog extends javax.swing.JDialog {

    /**
     * Creates new form AlterarVendaJDialog
     */
    ButtonColumn botao = null;
    ButtonColumn botao2 = null;
    Venda venda = new Venda();
    List<Servico> sList;
    List<Produto> pList;
    static Double valor = 0.00;

    public AlterarVendaJDialog(java.awt.Frame parent, boolean modal, int cod) {
        super(parent, modal);
        initComponents();
        VendaDao vendaDao = new VendaDao();
        PVProdutoDao pvpprodutoDao = new PVProdutoDao();
        SVServicoDao svsservicoDao = new SVServicoDao();
        try {
            venda = vendaDao.consultarPorCod(cod);
            pList = pvpprodutoDao.consultarPorCdvenda(cod);
            sList = svsservicoDao.consultarPorCdvenda(cod);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar a venda selecionada : " + ex.getMessage());
        }
        setSize(725, 648);
        setResizable(false);
        preencherJTable1(sList);
        preencherJTable2Primeira(pList);
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = dateFormat.format(venda.getDatavenda());
        dataVenda.setText(dataFormatada);

        Double precototal = 0.0;
        for (int i = 0; i < sList.size(); i++) {
            precototal = precototal + sList.get(i).getValor();
        }
        for (int i = 0; i < pList.size(); i++) {
            precototal = precototal + (pList.get(i).getQuantidade() * pList.get(i).getPreco());
        }
        campoModelo.setText(venda.getModelo());
        campoNome.setText(venda.getNome());
        campoPlaca.setText(venda.getPlacaCarro());
        valor = precototal;
        atualizarTotal(precototal);
    }

    public void setValor(Double valor) {
        this.valor = valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dataVenda = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoPlaca = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("AAA-####");
            campoPlaca = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        labelData = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        precoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Venda");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-voltar-32.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(0, 255, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-salvar-32.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("DATA DA VENDA");

        dataVenda.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(dataVenda)
                .addGap(82, 82, 82))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dataVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Placa : ");

        campoPlaca.setColumns(7);
        campoPlaca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        campoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPlacaActionPerformed(evt);
            }
        });

        labelData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(labelData)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelData))
                .addGap(2, 2, 2))
        );

        jLabel3.setText("Modelo :");

        campoModelo.setColumns(7);
        campoModelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setText("Nome do cliente:");

        campoNome.setColumns(15);
        campoNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(campoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Serviços");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Serviço", "Valor Atual", "Código"
            }
        ));
        jTable1.setRowHeight(32);
        jScrollPane3.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-adicionar-24.png"))); // NOI18N
        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Produtos");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-adicionar-24.png"))); // NOI18N
        jButton6.setText("incluir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Valor Atual", "Quantidade", "Código"
            }
        ));
        jTable2.setRowHeight(32);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Valor da venda: R$");

        precoTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        precoTotal.setForeground(new java.awt.Color(255, 51, 0));
        precoTotal.setText("0,00");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(precoTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel14, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void preencherJTable1(List<Servico> sList) {
        String[] colunas = new String[]{"ID", "Descrição", "Preço", "Excluir"};
        String[][] dados = new String[sList.size()][3];
        for (int i = 0; i < sList.size(); i++) {
            Servico s = sList.get(i);
            dados[i][0] = s.getCdServico() + "";
            String valorstr = s.getValor()+"";          
            valorstr = valorstr.replace(".", ",");
            String [] valorseparado = valorstr.split(",");
            if(valorseparado[1].length() == 1){
                valorseparado[1] = valorseparado[1]+"0";
            }
            valorstr = valorseparado[0] +","+ valorseparado[1];
            dados[i][2] = valorstr;
            dados[i][1] = s.getDescricao();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                dados, colunas
        ));
        try {
            botao = new ButtonColumn(this.jTable1, 3, sList, null, this);
        } catch (IOException ex) {
            Logger.getLogger(AlterarVendaJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void preencherJTable2(List<Produto> sList) {
        String[] colunas = new String[]{"ID", "Nome", "Preço", "Quantidade", "Excluir"};
        String[][] dados = new String[sList.size()][4];
        for (int i = 0; i < sList.size(); i++) {
            Produto s = sList.get(i);

            dados[i][0] = s.getCdproduto() + "";
            dados[i][1] = s.getNome();
            Double precovalor = s.getPreco() * s.getQtdVenda();
            String valorstr = s.getPreco()+"";          
            valorstr = valorstr.replace(".", ",");
            String [] valorseparado = valorstr.split(",");
            if(valorseparado[1].length() == 1){
                valorseparado[1] = valorseparado[1]+"0";
            }
            valorstr = valorseparado[0] +","+ valorseparado[1];
            dados[i][2] = valorstr;
            dados[i][3] = s.getQtdVenda() + "";
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                dados, colunas
        ));
        try {
            botao2 = new ButtonColumn(this.jTable2, 4, sList, null, this);
        } catch (IOException ex) {
            Logger.getLogger(AlterarVendaJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void preencherJTable2Primeira(List<Produto> sList) {
        String[] colunas = new String[]{"ID", "Nome", "Preço", "Quantidade", "Excluir"};
        String[][] dados = new String[sList.size()][4];
        for (int i = 0; i < sList.size(); i++) {
            Produto s = sList.get(i);

            dados[i][0] = s.getCdproduto() + "";
            dados[i][1] = s.getNome();
            Double precovalor = s.getPreco() * s.getQuantidade();
            String preco = String.valueOf(precovalor);
            preco = preco.replace(".", ",");
            dados[i][2] = preco;
            dados[i][3] = s.getQuantidade() + "";
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                dados, colunas
        ));
        try {
            botao2 = new ButtonColumn(this.jTable2, 4, sList, null, this);
        } catch (IOException ex) {
            Logger.getLogger(AlterarVendaJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //botão que inclui servicos prestados na venda
        ServicoSelecionarJDialog ps = new ServicoSelecionarJDialog(null, true);
        ps.setVisible(true);

        Servico s = ps.getServico();
        if (s != null) {
            this.sList.add(s);
            preencherJTable1(sList);
        }
        if (s != null) {
            valor = valor + s.getValor();
            atualizarTotal(valor);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Botão para fechar a label
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Botão para salvar a venda
        SVServicoDao svservico = new SVServicoDao();
        PVProdutoDao pvproduto = new PVProdutoDao();
        Venda v = new Venda();
        v.setNome(campoNome.getText());
        v.setPlacaCarro(campoPlaca.getText());
        v.setModelo(campoModelo.getText());
        String precototal = precoTotal.getText();
        precototal = precototal.replace(",", ".");
        v.setPrecoTotal(Double.parseDouble(precototal));
        PrincipalJFrame principal = new PrincipalJFrame();
        v.setCdFuncionario(venda.getCdFuncionario());
        v.setObsoleto(venda.isObsoleto());
        v.setSituacao(venda.getSituacao());
        v.setCdVenda(venda.getCdVenda());
        VendaDao dao = new VendaDao();
        v.setDatavenda(venda.getDatavenda());
        ServicoDao servicoDao = new ServicoDao();
        ProdutoDao produtoDao = new ProdutoDao();
        List<Servico> sList2 = new ArrayList<Servico>();
        List<Produto> pList2 = new ArrayList<Produto>();

        try {
            dao.Alterar(v);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar venda : " + ex.getMessage());
        }
        if (pList != null) {
            try {
                pvproduto.excluirProdutoVenda(v.getCdVenda());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir produtos antigos : " + ex.getMessage());
            }
        }
        if (sList != null) {
            try {
                svservico.excluirServicoVenda(v.getCdVenda());
            } catch (Exception ex) {
                Logger.getLogger(AlterarVendaJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        String[] cdServicosString = new String[jTable1.getRowCount()];
        int[] cdServicos = new int[jTable1.getRowCount()];
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getValueAt(i, 0) != null) {
                cdServicosString[i] = (String) jTable1.getValueAt(i, 0);
                cdServicos[i] = Integer.parseInt(cdServicosString[i]);
                try {
                    sList2.add(servicoDao.consultarPorCod(cdServicos[i]));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao consultar serviços da tabela : " + ex.getMessage());
                }

            }
        }
        int[] qtd = new int[jTable2.getRowCount()];
        String[] cdProdutosString = new String[jTable2.getRowCount()];
        int[] cdProdutos = new int[jTable2.getRowCount()];
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            if (jTable2.getValueAt(i, 0) != null) {
                cdProdutosString[i] = (String) jTable2.getValueAt(i, 0);
                cdProdutos[i] = Integer.parseInt(cdProdutosString[i]);
                qtd[i] = Integer.parseInt((String) jTable2.getValueAt(i, 3));
                try {
                    pList2.add(produtoDao.consultarPorCod(cdProdutos[i]));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao consultar produtos da tabela : " + ex.getMessage());
                }

            }
        }

        try {
            if (sList2.size() != 0) {
                for (int i = 0; i < sList2.size(); i++) {
                    svservico.inserir(v.getCdVenda(), sList2.get(i));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir nova Venda e seus servicos : " + ex.getMessage());
        }
        try {
            if (pList.size() != 0) {
                for (int i = 0; i < this.pList.size(); i++) {
                    pvproduto.inserir(v.getCdVenda(), pList2.get(i), qtd[i]);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao inserir nova Venda e seus produtos : " + ex.getMessage());
        }

        JOptionPane.showMessageDialog(this, "Venda alterada com sucesso.");
        
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed
    public void atualizarTotal(Double preco) {
        String repreco = preco + "";
        repreco = repreco.replace(".", ",");
        this.precoTotal.setText(repreco + "0");
    }

    public Double getPrecoTotal() {
        String preco = this.precoTotal.getText();
        preco = preco.replace(",", ".");
        Double precoTotal = Double.parseDouble(preco);
        return precoTotal;
    }
    private void campoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPlacaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //botão que inclui produtos vendidos
        ProdutoSelecionarJDialog ps = new ProdutoSelecionarJDialog(null, true);
        ps.setVisible(true);

        Produto s = ps.getProduto();

        if (s != null) {
            this.pList.add(s);
        }

        int qtd = ps.getQtd();

        if (s != null) {
            valor = valor + (s.getPreco() * qtd);
        }
        ProdutoDao produtoDao = new ProdutoDao();
        if (qtd != 0) {
            s.setQuantidade(s.getQuantidade() - qtd);
            try {
                produtoDao.Alterar(s);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao buscar produtos do estoque: " + ex.getMessage());
            }
        }
        preencherJTable2(this.pList);
        atualizarTotal(valor);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarVendaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarVendaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarVendaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarVendaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlterarVendaJDialog dialog = new AlterarVendaJDialog(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPlaca;
    private javax.swing.JLabel dataVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel precoTotal;
    // End of variables declaration//GEN-END:variables

}
