/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.trab.oficinamecanica.view.venda;

import br.cefet.trab.oficinamecanica.dao.ReciboRelatorioDao;
import br.cefet.trab.oficinamecanica.dao.VendaDao;
import br.cefet.trab.oficinamecanica.entidade.Funcionario;
import br.cefet.trab.oficinamecanica.entidade.Produto;
import br.cefet.trab.oficinamecanica.entidade.ReciboRelatorio;
import br.cefet.trab.oficinamecanica.entidade.Servico;
import br.cefet.trab.oficinamecanica.entidade.Venda;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 * Interface de vendas
 * @author arthur
 */
public class VendaJFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venda
     */
    private Produto produto = new Produto();
    private Venda venda = new Venda();
    private Funcionario funcionario = new Funcionario();
    private Servico servico = new Servico();
    private Double valor = 0.00;
    private List<Servico> sList = new ArrayList<Servico>();
    private int cdVenda;
    private int cdfuncionario;
    
    public VendaJFrame() {
        initComponents();
        
        
        
    }
    public void setCdfuncionario(int cdfuncionario){
        this.cdfuncionario = cdfuncionario;
       
    }
    
    public void desligarbotoes() {
        botaoFinalizar.setEnabled(false);
        botaoObsoleto.setEnabled(false);
        botaoEditar.setEnabled(false);
        botaoRecibo.setEnabled(false);
    }
     public void mandarpreencher() {
        List<Venda> vList = new ArrayList<Venda>();
        VendaDao vendaDao = new VendaDao();
        try {
            
            vList = vendaDao.consultarTodos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao consultar Vendas :- " + e.getMessage(), "Erro de Consulta", JOptionPane.ERROR_MESSAGE);
        }
        preencherJTable(vList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        botaoFinalizar = new javax.swing.JButton();
        botaoObsoleto = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoRecibo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel12.setText("jLabel12");

        jLabel28.setText("jLabel28");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");

        jPanel74.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel29.setText("Nome do cliente :");
        jPanel74.add(jLabel29);

        jTextField3.setColumns(15);
        jPanel74.add(jTextField3);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-procurar-usuário-masculino-24.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel74.add(jButton7);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        botaoFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-pagar-32.png"))); // NOI18N
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });

        botaoObsoleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-remover-32.png"))); // NOI18N
        botaoObsoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoObsoletoActionPerformed(evt);
            }
        });

        botaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-voltar-32.png"))); // NOI18N
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-adicionar-o-carrinho-de-compras-32.png"))); // NOI18N
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        jLabel2.setText("Finalizar");

        jLabel3.setText("obsoleto");

        jLabel5.setText("Nova");

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-editar-32.png"))); // NOI18N
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("Editar");

        botaoRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/cefet/trab/oficinamecanica/images/icons8-enviar-para-a-impressora-32.png"))); // NOI18N
        botaoRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReciboActionPerformed(evt);
            }
        });

        jLabel4.setText("Recibo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botaoVoltar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoFinalizar)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoObsoleto)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoNovo)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoEditar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoRecibo)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botaoObsoleto)
                        .addComponent(botaoFinalizar)
                        .addComponent(botaoVoltar)
                        .addComponent(botaoNovo))
                    .addComponent(botaoEditar)
                    .addComponent(botaoRecibo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel35, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        
    public static void emitirRelatorio(List<ReciboRelatorio> recibo) {
        String reportSource = "../report/recibo.jasper";

        Map<String, Object> params = new HashMap<String, Object>();

        try {
            JRBeanCollectionDataSource jrBean = new JRBeanCollectionDataSource(recibo, false);
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportSource, params, jrBean);

            //JasperExportManager.exportReportToPdfFile(jasperPrint, reportDest);
                    
            
            JasperViewer jv = new JasperViewer(jasperPrint,false);
            jv.setTitle("Relatório");
            Image image = Toolkit.getDefaultToolkit().getImage("src/br/cefet/trab/oficinamecanica/images/relatorio.png");
           
            jv.setIconImage(image);
            jv.setVisible(true);
        } catch (JRException ex) {
            ex.printStackTrace();
        }

    }
    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int linha = jTable1.getSelectedRow();
        botaoEditar.setEnabled(true);
        botaoFinalizar.setEnabled(true);
        botaoObsoleto.setEnabled(true);
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        String situacao = tModel.getValueAt(linha, 3).toString();
        if(situacao.equals("Pago")){
            botaoRecibo.setEnabled(true);
        }else{
            botaoRecibo.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void botaoReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReciboActionPerformed
        // botão que gera o recibo da venda
        int linha = jTable1.getSelectedRow();
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        int cod = getCodVendaFromTable();
        ReciboRelatorio reciboR = new ReciboRelatorio();
        ReciboRelatorioDao reciboRDao = new ReciboRelatorioDao();
        List<ReciboRelatorio> recibos = null;
        try {
            recibos = reciboRDao.consultar(cod);
        } catch (Exception ex) {
            Logger.getLogger(InserirVendaJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        emitirRelatorio(recibos);
    }//GEN-LAST:event_botaoReciboActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        //Botão responsavel por editar as informacoes de venda
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        int cod = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        AlterarVendaJDialog alterar = new AlterarVendaJDialog(null, true, cod);
        alterar.setVisible(true);
        mandarpreencher();
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        // Botão responsavel por fazer nova venda
        InserirVendaJDialog inserir = new InserirVendaJDialog(null, true);
        inserir.setVisible(true);
        mandarpreencher();
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoObsoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoObsoletoActionPerformed
        // Botão responsavel por excluir a venda
        int linha = jTable1.getSelectedRow();
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        int cod = getCodVendaFromTable();

        int opt = JOptionPane.showConfirmDialog(this, "Quer realmente tornar obsoleto a Venda de código " + cod + "?");
        if (opt == JOptionPane.OK_OPTION) {
            try {

                VendaDao dao = new VendaDao();
                Venda venda = dao.consultarPorCod(cod);
                venda.setObsoleto(true);
                dao.Alterar(venda);

                tModel.removeRow(linha);
                JOptionPane.showMessageDialog(rootPane, "feito com sucesso");
                desligarbotoes();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao tonar obsoleto venda :- " + e.getMessage(), "Erro de alteração", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_botaoObsoletoActionPerformed

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        // Botão responsavel por finalizar a venda

        int linha = jTable1.getSelectedRow();
        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();
        int cod = getCodVendaFromTable();
        VendaDao vendaDao = new VendaDao();
        try {
            this.venda = vendaDao.consultarPorCod(cod);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao finalizar venda :- " + e.getMessage(), "Erro de Consulta", JOptionPane.ERROR_MESSAGE);
        }
        if (this.venda.getSituacao().equalsIgnoreCase("Não Pago")) {
            this.venda.setSituacao("Pago");
            try {
                vendaDao.Alterar(this.venda);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao finalizar venda :- " + e.getMessage(), "Erro de alteração", JOptionPane.ERROR_MESSAGE);
            }
            this.venda = null;
            mandarpreencher();
            desligarbotoes();
            JOptionPane.showMessageDialog(rootPane, "Pago com sucesso, gerando recibo");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Já está pago, gerando recibo");
        }
        
    }//GEN-LAST:event_botaoFinalizarActionPerformed
    public int getCodVendaFromTable() {
        int linha = jTable1.getSelectedRow();

        DefaultTableModel tModel = (DefaultTableModel) jTable1.getModel();

        String codStr = tModel.getValueAt(linha, 0).toString();
        int cod = Integer.parseInt(codStr);
        return cod;
    }

    private void preencherJTable(List<Venda> sList) {
        String[] colunas = new String[]{"ID", "Nome", "Preço-Total", "Situação", "Data-Venda"};
        String[][] dados = new String[sList.size()][5];
        for (int i = 0; i < sList.size(); i++) {
            Venda s = sList.get(i);
            if (s.isObsoleto() != true) {
                dados[i][0] = s.getCdVenda() + "";
                dados[i][1] = s.getNome();
                String valorstr = s.getPrecoTotal()+"";          
            valorstr = valorstr.replace(".", ",");
            String [] valorseparado = valorstr.split(",");
            if(valorseparado[1].length() == 1){
                valorseparado[1] = valorseparado[1]+"0";
            }
            valorstr = valorseparado[0] +","+ valorseparado[1];
                dados[i][2] = valorstr;
                dados[i][3] = s.getSituacao();
                dados[i][4] = s.getDatavenda() + "";
            }
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                dados, colunas
        ));
        desligarbotoes();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoObsoleto;
    private javax.swing.JButton botaoRecibo;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
